s3:
  bucket_name: "reddit-backo"
  s3_key: "rawData/jumiatv.csv"

postgres:
  database: "postgres"
  port: 5433
  host: "localhost"
  username: "postgres"
  table:
    - "jumiaTV"
    - "jumiaPhones"

local:
  file_path: "C:\\Users\\Admin\\Desktop\\jumia-DE\\ETL\\jumiatv.csv"
